[package]
name = "silkroad"
version = "0.0.0"
authors = ["GengTeng <me@gteng.org>"]
edition = "2018"
description = "Yet another crates.io mirroring tool."
license = "MIT"

[dependencies]
actix-web =  { version = "1.0.2", features = ["rust-tls"] }
actix-files = "0.1.2"
actix-rt = "0.2"
futures = "0.1"
serde = "1.0.92"
serde_json = "1.0.39"
serde_derive = "1.0.92"
structopt = "0.2"
rustls = "0.15"
git2 = "0.9.1"
failure = "0.1.5"

[[bin]]
path = "src/main.rs"
name = "skrd"